/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package awaball;

import awaball.classes.ChiffrementDechiffrementAsymetrique;
import awaball.classes.ChiffrementDechiffrementSymetrique;
import java.io.File;
import java.security.InvalidKeyException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.NoSuchPaddingException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Awa Ball
 */
public class Chiffrement extends javax.swing.JInternalFrame {

    /**
     * Creates new form GenerationCles
     */
    public Chiffrement() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI b = (BasicInternalFrameUI) this.getUI();
        b.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        messageUpload = new javax.swing.JButton();
        message = new javax.swing.JTextField();
        keyUpload = new javax.swing.JButton();
        key = new javax.swing.JTextField();
        cipher = new javax.swing.JButton();
        algorithme = new javax.swing.JComboBox<>();
        typeChiffrement = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(890, 608));

        jPanel1.setPreferredSize(new java.awt.Dimension(874, 550));

        messageUpload.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        messageUpload.setText("Selectionner le message");
        messageUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageUploadActionPerformed(evt);
            }
        });

        message.setEditable(false);
        message.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageActionPerformed(evt);
            }
        });

        keyUpload.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        keyUpload.setText("Selectionner la clé");
        keyUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keyUploadActionPerformed(evt);
            }
        });

        key.setEditable(false);
        key.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keyActionPerformed(evt);
            }
        });

        cipher.setBackground(new java.awt.Color(0, 153, 255));
        cipher.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cipher.setForeground(new java.awt.Color(255, 255, 255));
        cipher.setText("Chiffrer");
        cipher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cipherActionPerformed(evt);
            }
        });

        algorithme.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        algorithme.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Algorithme " }));
        algorithme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                algorithmeActionPerformed(evt);
            }
        });

        typeChiffrement.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        typeChiffrement.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chiffrement", "Symetrique", "Asymetrique", " " }));
        typeChiffrement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeChiffrementActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(message, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                        .addComponent(typeChiffrement, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(key, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(algorithme, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(messageUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(keyUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addComponent(cipher, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeChiffrement, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(algorithme, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(key, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(keyUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(cipher, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void messageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_messageActionPerformed

    private void keyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keyActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_keyActionPerformed

    private void messageUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageUploadActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showOpenDialog(jPanel1);
        File file = fileChooser.getSelectedFile();
        String fichier = file.getAbsolutePath();
        message.setText(fichier);
        
        
        
    }//GEN-LAST:event_messageUploadActionPerformed

    private void keyUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keyUploadActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showOpenDialog(jPanel1);
        File file = fileChooser.getSelectedFile();
        String cle = file.getAbsolutePath();
        key.setText(cle);
    }//GEN-LAST:event_keyUploadActionPerformed

    private void cipherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cipherActionPerformed
        // TODO add your handling code here:
        
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.showSaveDialog(jPanel1);
        File file = fileChooser.getSelectedFile();
        String path =  file.getAbsolutePath();
        String mess = message.getText();
        String clef = key.getText();
        String algo = (String) algorithme.getSelectedItem();
        
       
         if (typeChiffrement.getSelectedItem().equals("Symetrique")){
               try {
            ChiffrementDechiffrementSymetrique.encrypterFichier(algo, clef, mess, path);
            JOptionPane.showMessageDialog(rootPane, "Message Chiffré");
        } catch (NoSuchPaddingException ex) {
            Logger.getLogger(Chiffrement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvalidKeyException ex) {
            Logger.getLogger(Chiffrement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Chiffrement.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         }
         else  if (typeChiffrement.getSelectedItem().equals("Asymetrique")){
               try {
            ChiffrementDechiffrementAsymetrique.encrypt(algo, clef, mess, path);
            JOptionPane.showMessageDialog(rootPane, "Message Chiffré");
        } catch (NoSuchPaddingException ex) {
            Logger.getLogger(Chiffrement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvalidKeyException ex) {
            Logger.getLogger(Chiffrement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Chiffrement.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         }
        
        
    }//GEN-LAST:event_cipherActionPerformed

    private void algorithmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_algorithmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_algorithmeActionPerformed

    private void typeChiffrementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeChiffrementActionPerformed
        // TODO add your handling code here:
        String algoSymetrique [] = {"Algorithme", "AES", "DES"};
        String algoAsymetrique [] = {"Algorithme", "RSA"};
        String choix = (String) typeChiffrement.getSelectedItem();
        if (choix.equals("Symetrique")){
            keyUpload.setText("Clé Secréte");
            algorithme.setModel(new javax.swing.DefaultComboBoxModel<>(algoSymetrique));
        }
        else if (choix.equals("Asymetrique")){
            keyUpload.setText("Clé Publique");
            algorithme.setModel(new javax.swing.DefaultComboBoxModel<>(algoAsymetrique));
            
        }
        
    }//GEN-LAST:event_typeChiffrementActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> algorithme;
    private javax.swing.JButton cipher;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField key;
    private javax.swing.JButton keyUpload;
    private javax.swing.JTextField message;
    private javax.swing.JButton messageUpload;
    private javax.swing.JComboBox<String> typeChiffrement;
    // End of variables declaration//GEN-END:variables
}
