/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package awaball;

/**
 *
 * @author Awa Ball
 */
public class CryptographiesOperations extends javax.swing.JFrame {

    /**
     * Creates new form Cryptographies
     */
    public CryptographiesOperations() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4MainTitle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2MainMenu = new javax.swing.JPanel();
        buttonSignature = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        accueil = new javax.swing.JButton();
        jPanel6Menu = new javax.swing.JPanel();
        generateKey = new javax.swing.JButton();
        buttonDechiffrement = new javax.swing.JButton();
        buttonChiffrement = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setAutoscrolls(true);

        jPanel4MainTitle.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Liberation Sans", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("APPLICATION CRYPTOGRAPHIQUE");

        javax.swing.GroupLayout jPanel4MainTitleLayout = new javax.swing.GroupLayout(jPanel4MainTitle);
        jPanel4MainTitle.setLayout(jPanel4MainTitleLayout);
        jPanel4MainTitleLayout.setHorizontalGroup(
            jPanel4MainTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4MainTitleLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel1)
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel4MainTitleLayout.setVerticalGroup(
            jPanel4MainTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4MainTitleLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2MainMenu.setBackground(new java.awt.Color(51, 0, 153));

        buttonSignature.setBackground(new java.awt.Color(0, 102, 255));
        buttonSignature.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonSignature.setForeground(new java.awt.Color(255, 255, 255));
        buttonSignature.setText("Signature");
        buttonSignature.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSignatureMouseClicked(evt);
            }
        });
        buttonSignature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSignatureActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 102, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Hachage");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        accueil.setBackground(new java.awt.Color(0, 102, 255));
        accueil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        accueil.setForeground(new java.awt.Color(255, 255, 255));
        accueil.setText("Accueil");
        accueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accueilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2MainMenuLayout = new javax.swing.GroupLayout(jPanel2MainMenu);
        jPanel2MainMenu.setLayout(jPanel2MainMenuLayout);
        jPanel2MainMenuLayout.setHorizontalGroup(
            jPanel2MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2MainMenuLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel2MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonSignature, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(accueil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(68, 68, 68))
        );
        jPanel2MainMenuLayout.setVerticalGroup(
            jPanel2MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2MainMenuLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(buttonSignature, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addComponent(accueil, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );

        jPanel6Menu.setBackground(new java.awt.Color(0, 102, 255));

        generateKey.setBackground(new java.awt.Color(0, 51, 204));
        generateKey.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        generateKey.setForeground(new java.awt.Color(255, 255, 255));
        generateKey.setText("Génération de clés");
        generateKey.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generateKeyMouseClicked(evt);
            }
        });
        generateKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateKeyActionPerformed(evt);
            }
        });

        buttonDechiffrement.setBackground(new java.awt.Color(0, 51, 204));
        buttonDechiffrement.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonDechiffrement.setForeground(new java.awt.Color(255, 255, 255));
        buttonDechiffrement.setText("Dechiffrement");
        buttonDechiffrement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonDechiffrementMouseClicked(evt);
            }
        });

        buttonChiffrement.setBackground(new java.awt.Color(0, 51, 204));
        buttonChiffrement.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buttonChiffrement.setForeground(new java.awt.Color(255, 255, 255));
        buttonChiffrement.setText("Chiffrement");
        buttonChiffrement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonChiffrementMouseClicked(evt);
            }
        });
        buttonChiffrement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonChiffrementActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6MenuLayout = new javax.swing.GroupLayout(jPanel6Menu);
        jPanel6Menu.setLayout(jPanel6MenuLayout);
        jPanel6MenuLayout.setHorizontalGroup(
            jPanel6MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6MenuLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(generateKey)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonChiffrement)
                .addGap(165, 165, 165)
                .addComponent(buttonDechiffrement)
                .addGap(49, 49, 49))
        );
        jPanel6MenuLayout.setVerticalGroup(
            jPanel6MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6MenuLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel6MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generateKey, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonChiffrement, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDechiffrement, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/awaball/icons/icons8-chiffrement-des-données-40.png"))); // NOI18N
        jLabel2.setText("Protégez vos communications avec le pouvoir de la cryptographie.");

        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2MainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4MainTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6Menu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addComponent(jDesktopPane1)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4MainTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDesktopPane1))
                    .addComponent(jPanel2MainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateKeyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generateKeyMouseClicked
        // TODO add your handling code here:
        GenerationCles key = new GenerationCles();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(key).setVisible(true);

        //        Dechiffrement d = new Dechiffrement();
        //        jDesktopPane1.removeAll();
        //        jDesktopPane1.add(d).setVisible(true);

    }//GEN-LAST:event_generateKeyMouseClicked

    private void generateKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateKeyActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_generateKeyActionPerformed

    private void buttonDechiffrementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDechiffrementMouseClicked
        // TODO add your handling code here:
        Dechiffrement d = new Dechiffrement();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(d).setVisible(true);
    }//GEN-LAST:event_buttonDechiffrementMouseClicked

    private void buttonChiffrementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonChiffrementMouseClicked
        // TODO add your handling code here:
        Chiffrement d = new Chiffrement();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(d).setVisible(true);
    }//GEN-LAST:event_buttonChiffrementMouseClicked

    private void buttonChiffrementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonChiffrementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonChiffrementActionPerformed

    private void buttonSignatureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSignatureMouseClicked
        // TODO add your handling code here:
        Signature s = new Signature();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(s).setVisible(true);
    }//GEN-LAST:event_buttonSignatureMouseClicked

    private void buttonSignatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSignatureActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_buttonSignatureActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        Hachage h = new Hachage();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(h).setVisible(true);

    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton3ActionPerformed

    private void accueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accueilActionPerformed
        // TODO add your handling code here:
         dispose();
        Accueil c = new Accueil();
        c.setLocationRelativeTo(null);
        c.setVisible(true);
    }//GEN-LAST:event_accueilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CryptographiesOperations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CryptographiesOperations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CryptographiesOperations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CryptographiesOperations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CryptographiesOperations().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accueil;
    private javax.swing.JButton buttonChiffrement;
    private javax.swing.JButton buttonDechiffrement;
    private javax.swing.JButton buttonSignature;
    private javax.swing.JButton generateKey;
    private javax.swing.JButton jButton3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2MainMenu;
    private javax.swing.JPanel jPanel4MainTitle;
    private javax.swing.JPanel jPanel6Menu;
    // End of variables declaration//GEN-END:variables
}
